name: golang-pipeline
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1

  test_unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Run Unit Tests
        run: make test

  test_integration:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Download apps
        uses: actions/download-artifact@v2
        with:
          name: Build apps
      - name: Run Integration Tests
        run: make test_integration
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17'
    - name: Build apps
      run: make build
    - name: Upload server
      uses: actions/upload-artifact@v2
      with:
        name: Build apps
        path: ab-srv
    - name: Upload client
      uses: actions/upload-artifact@v2
      with:
        name: Build apps
        path: ab-client
